//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MN.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MN.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ColorSchemeAccentBlue {
            get {
                return ResourceManager.GetString("ColorSchemeAccentBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorSchemeAccentGreen {
            get {
                return ResourceManager.GetString("ColorSchemeAccentGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string ColorSchemeAccentOrange {
            get {
                return ResourceManager.GetString("ColorSchemeAccentOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ColorSchemeBaseDark {
            get {
                return ResourceManager.GetString("ColorSchemeBaseDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ColorSchemeBaseLight {
            get {
                return ResourceManager.GetString("ColorSchemeBaseLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogButtonCancel {
            get {
                return ResourceManager.GetString("DialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogButtonNo {
            get {
                return ResourceManager.GetString("DialogButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogButtonOK {
            get {
                return ResourceManager.GetString("DialogButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogButtonYes {
            get {
                return ResourceManager.GetString("DialogButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string FolderExplorerCollapseAll {
            get {
                return ResourceManager.GetString("FolderExplorerCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string FolderExplorerComputer {
            get {
                return ResourceManager.GetString("FolderExplorerComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FolderExplorerDelete {
            get {
                return ResourceManager.GetString("FolderExplorerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string FolderExplorerDeleteConfirmation {
            get {
                return ResourceManager.GetString("FolderExplorerDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to move &quot;{0}&quot; to Recycle Bin?.
        /// </summary>
        public static string FolderExplorerDeleteMessage {
            get {
                return ResourceManager.GetString("FolderExplorerDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        public static string FolderExplorerNewDirectory {
            get {
                return ResourceManager.GetString("FolderExplorerNewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string FolderExplorerNewFile {
            get {
                return ResourceManager.GetString("FolderExplorerNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string FolderExplorerRefresh {
            get {
                return ResourceManager.GetString("FolderExplorerRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string FolderExplorerRename {
            get {
                return ResourceManager.GetString("FolderExplorerRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files.
        /// </summary>
        public static string FolderExplorerShowFiles {
            get {
                return ResourceManager.GetString("FolderExplorerShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden elements.
        /// </summary>
        public static string FolderExplorerShowHidden {
            get {
                return ResourceManager.GetString("FolderExplorerShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show system elements.
        /// </summary>
        public static string FolderExplorerShowSystem {
            get {
                return ResourceManager.GetString("FolderExplorerShowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Explorer.
        /// </summary>
        public static string FolderExplorerTitle {
            get {
                return ResourceManager.GetString("FolderExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string MenuAccent {
            get {
                return ResourceManager.GetString("MenuAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ShellWindowClose {
            get {
                return ResourceManager.GetString("ShellWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string ShellWindowMaximize {
            get {
                return ResourceManager.GetString("ShellWindowMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string ShellWindowMinimize {
            get {
                return ResourceManager.GetString("ShellWindowMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ShellWindowRestore {
            get {
                return ResourceManager.GetString("ShellWindowRestore", resourceCulture);
            }
        }
    }
}
